### ISSUE TITLE
is it possible to use this with Voila?

### ISSUE THREAD

**Issue by jgunstone** [jupyterlab-contrib/jupyterlab-filesystem-access#62]
this extension is awesome! I've only just come across it, and once #22 is resolved you can see how this will deliver a great user experience. 

for voila apps, is it possible to also make use this plugin? 
giving apps the ability to: store appdata in a user defined folder, output results outcomes from voila apps in user defined folder would be super useful. 

thanks!

**Comment by martinRenou** [comment]
Now that voila is a jupyterlab-based application for the front-end, it may be possible for the Voila app to interact with it in some way.

Although the kernel will not know anything about it (just like the jupyterlab case, because it's a pure front-end plugin), so there will be very little things you can do with it, e.g. "output results outcomes from voila apps" will not be possible.

On the other hand, Voici having the kernel running in the web page, it should potentially be able to save outputs in a local folder using this plugin. See https://github.com/voila-dashboards/voici/issues/102

**Comment by jgunstone** [comment]
"the kernel will not know anything about it" - 
Just fiddling around I think I'm beginning to better understand how this works. When opening a Notebook in user folder the `os.getcwd()` is still the root, so the notebook kernel has no knowledge of the filesystem. same for the kernel. so if you create a python file in the user folder - you have no way of running that file? 

and I guess that these limitations are inherent to the way that access is provided ?

**Comment by martinRenou** [comment]
> and I guess that these limitations are inherent to the way that access is provided ?

Yeah it's a structural limitation:
- the kernel runs on the server and only has access to the file system that's local to the server
- the jupyterlab-filesystem-access uses the Chrome browser APIs to open a "local" client folder from the JupyterLab UI. In the case where you serve your jupyterlab on localhost, it happens to be the same machine (client is the same machine as the server).

The kernel actually does not know anything about the client. It could be JupyterLab, Voila, etc, the kernel does not know. It could very well be multiple clients as well. So the fact that the client makes use of browser APIs to access local client files is really not something the kernel can know.

**Comment by jgunstone** [comment]
okay cool - yes it was beginning to feel like a magic catch all solution to many long-running problems we've been having so the constraints make sense! thanks for talking it through. 
 
I'll close the issue as I think my questions are answered - thanks!
